/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import dao.TaiKhoan_DAO;
import entity.TaiKhoan;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class DoiMatKhau extends javax.swing.JFrame {
    public static TaiKhoan tk;
    public TaiKhoan_DAO tk_dao = new TaiKhoan_DAO();
    public static JFrame main;
    /**
     * Creates new form ádksa
     */
    public DoiMatKhau(TaiKhoan tk, JFrame main) {
        initComponents();
        this.tk = tk;
        this.main = main;
        
        setLocationRelativeTo(null);
        setDefaultCloseOperation(1);
        setSize(570, 360);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_Top = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnl_Center = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pass_MatKhauMoi = new javax.swing.JPasswordField();
        pass_MatKhauHienTai = new javax.swing.JPasswordField();
        btn_XacNhan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnl_Top.setBackground(new java.awt.Color(153, 153, 0));
        pnl_Top.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 1, 15, 1));
        pnl_Top.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Đổi mật khẩu");
        pnl_Top.add(jLabel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnl_Top, java.awt.BorderLayout.PAGE_START);

        pnl_Center.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Mật khẩu mới:");
        pnl_Center.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Mật khẩu hiện tại:");
        pnl_Center.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        pass_MatKhauMoi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        pass_MatKhauMoi.setPreferredSize(new java.awt.Dimension(68, 45));
        pnl_Center.add(pass_MatKhauMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 270, -1));

        pass_MatKhauHienTai.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        pass_MatKhauHienTai.setPreferredSize(new java.awt.Dimension(68, 45));
        pnl_Center.add(pass_MatKhauHienTai, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 270, -1));

        btn_XacNhan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_XacNhan.setText("Xác nhận");
        btn_XacNhan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_XacNhanMouseClicked(evt);
            }
        });
        pnl_Center.add(btn_XacNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 170, 50));

        getContentPane().add(pnl_Center, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_XacNhanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_XacNhanMouseClicked
        // TODO add your handling code here:
        String matKhauCu = pass_MatKhauHienTai.getText();
        String matKhauMoi = pass_MatKhauMoi.getText();
        
        // kiem tra mk cu đung hay sai
        if(tk.getPassword().equals(matKhauCu)) {
            tk_dao.CapNhatTK(tk.getMaTK(), matKhauMoi);
            main.setVisible(false);
            this.setVisible(false);
            MainView gui_login = new MainView();
//            this.setVisible(false);
            gui_login.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(pnl_Top, "Mật khẩu hiện tại sai!!! Nhập lại!!!");
        }
    }//GEN-LAST:event_btn_XacNhanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoiMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoiMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoiMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoiMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoiMatKhau(tk, main).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_XacNhan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField pass_MatKhauHienTai;
    private javax.swing.JPasswordField pass_MatKhauMoi;
    private javax.swing.JPanel pnl_Center;
    private javax.swing.JPanel pnl_Top;
    // End of variables declaration//GEN-END:variables
}
