/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import dao.CTHD_NhapHang_DAO;
import dao.HoaDon_NCC_DAO;
import dao.NhaCungCap_DAO;
import dao.SanPham_DAO;
import entity.ChiTietHD_NCC;
import entity.HoaDonNCC;
import entity.NhaCungCap;
import entity.SanPham;
import java.time.LocalDateTime;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Asus
 */
public class Panel_inventory extends javax.swing.JPanel {
    private NhaCungCap_DAO ncc_dao = new NhaCungCap_DAO();
    private SanPham_DAO sp_dao = new SanPham_DAO();
    private HoaDon_NCC_DAO hdnh_dao = new HoaDon_NCC_DAO();
    private CTHD_NhapHang_DAO cthd_nh_dao = new CTHD_NhapHang_DAO();
    private double tongTien = 0;
    /**
     * Creates new form Panel_inventory
     */
    public Panel_inventory() {
        initComponents();
        
        DocDuLieuLenTableNCC();
        DocDuLieuLenComBoBox_DSNCC();
    }
    
    public void DocDuLieuLenComBoBox_DSNCC() {
        ArrayList<NhaCungCap> dsNCC = ncc_dao.getAllNCC();
        
        for(NhaCungCap ncc : dsNCC) {
            cbo_DSNCC.addItem(ncc);
        }
    }
    
    public boolean valiData_NCC() {
        String maNCC = txt_MaNCC.getText().toString().trim();
        String tenNCC = txt_TenNCC.getText().toString().trim();
        String email = txt_Email.getText().toString().trim();
        String sDT = txt_SDT.getText().toString().trim();
        String diaChi = txt_DiaChi.getText().toString().trim();
        
        if(maNCC.isEmpty() || (!maNCC.matches("^NCC\\d{3}$"))) {
            JOptionPane.showMessageDialog(this, "Mã NCC phải theo mẫu NCC001");
            return false;
        }
        
        if(tenNCC.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tên NCC không được rỗng!!!");
            return false;
        }
        
        if(email.isEmpty() || !email.matches("[a-zA-Z0-9]+@gmail.com")) {
            JOptionPane.showMessageDialog(this, "Email theo mẫu abc123@gmail.com");
            return false;
        }
        
        if(sDT.isEmpty() || !sDT.matches("0\\d{9}")) {
            JOptionPane.showMessageDialog(this, "Số điện thoại phải có 10 số");
            return false;
        }
        
        if(diaChi.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Địa chỉ khoogn được rỗng!!!");
            return false;
        }
                
        
        return true;
    }
    
    public void DocDuLieuLenTableNCC() {
        ArrayList<NhaCungCap> dsNCC = ncc_dao.getAllNCC();
        DefaultTableModel temp = (DefaultTableModel) table_NCC.getModel();
        
        for(NhaCungCap ncc : dsNCC) {
            Object[] obj = {ncc.getMaNCC(), ncc.getTenNCC(), ncc.getDiaChi(), ncc.getEmail(), ncc.getSDT()};
            
            temp.addRow(obj);
        }
    }
    
    public void XoaDuLieuTableNCC() {
        DefaultTableModel temp = (DefaultTableModel) table_NCC.getModel();
        temp.getDataVector().removeAllElements();
    }
    
    public NhaCungCap createNCC() {
        String maNCC = txt_MaNCC.getText().toString();
        String tenNCC = txt_TenNCC.getText().toString();
        String email = txt_Email.getText().toString();
        String sDT = txt_SDT.getText().toString();
        String diaChi = txt_DiaChi.getText().toString();
        
        NhaCungCap ncc = new NhaCungCap(maNCC, tenNCC, diaChi, sDT, email);
        
        return ncc;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Tabbed_NhapHang = new javax.swing.JTabbedPane();
        pnl_DanhSachNCC = new javax.swing.JPanel();
        pnl_NCC_ThongTin = new javax.swing.JPanel();
        pnl_ThongTin = new javax.swing.JPanel();
        lb_DiaChi = new javax.swing.JLabel();
        txt_Email = new javax.swing.JTextField();
        lb_Email = new javax.swing.JLabel();
        lb_SDT = new javax.swing.JLabel();
        lb_MaNCC = new javax.swing.JLabel();
        lb_TenNCC = new javax.swing.JLabel();
        btn_CapNhat = new javax.swing.JButton();
        btn_ThemMoi = new javax.swing.JButton();
        btn_XoaTrang = new javax.swing.JButton();
        txt_SDT = new javax.swing.JTextField();
        txt_DiaChi = new javax.swing.JTextField();
        txt_MaNCC = new javax.swing.JTextField();
        txt_TenNCC = new javax.swing.JTextField();
        pnl_TimKiem_NCC = new javax.swing.JPanel();
        txt_TimKiem_NCC = new javax.swing.JTextField();
        btn_TimKiem_NCC = new javax.swing.JButton();
        pnl_NCC_Table = new javax.swing.JPanel();
        scroll_NCC = new javax.swing.JScrollPane();
        table_NCC = new javax.swing.JTable();
        pnl_TaoPhieuNhap = new javax.swing.JPanel();
        pnl_DanhSachSP = new javax.swing.JPanel();
        scroll_DanhSachSP = new javax.swing.JScrollPane();
        table_DanhSachSP = new javax.swing.JTable();
        pnl_ThongTinNCC = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbo_DSNCC = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        area_ghiChu = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        txt_TongTien = new javax.swing.JTextField();
        btn_TaoHoaDonNCC = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        pnl_TimKiem = new javax.swing.JPanel();
        txt_TimKiem = new javax.swing.JTextField();
        btn_TimSP = new javax.swing.JButton();
        pnl_HoaDonNhapHang = new javax.swing.JPanel();
        pnl_Top = new javax.swing.JPanel();
        pnl_HDNH_TimKiem = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        pnl_BoLoc = new javax.swing.JPanel();
        pnl_LocNhanVien = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTextField4 = new javax.swing.JTextField();
        pnl_LocNCC = new javax.swing.JPanel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        pnl_LocTheoNgay = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        pnl_Center = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        pnl_DanhSachNCC.setLayout(new java.awt.BorderLayout());

        pnl_NCC_ThongTin.setPreferredSize(new java.awt.Dimension(10, 250));
        pnl_NCC_ThongTin.setLayout(new java.awt.BorderLayout());

        pnl_ThongTin.setMinimumSize(new java.awt.Dimension(10, 150));
        pnl_ThongTin.setPreferredSize(new java.awt.Dimension(10, 150));
        pnl_ThongTin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_DiaChi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_DiaChi.setText("Địa chỉ:");
        pnl_ThongTin.add(lb_DiaChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, -1, -1));

        txt_Email.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pnl_ThongTin.add(txt_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 310, 40));

        lb_Email.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_Email.setText("Email:");
        pnl_ThongTin.add(lb_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        lb_SDT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_SDT.setText("SĐT:");
        pnl_ThongTin.add(lb_SDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 20, -1, -1));

        lb_MaNCC.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_MaNCC.setText("Mã NCC:");
        pnl_ThongTin.add(lb_MaNCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        lb_TenNCC.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_TenNCC.setText("Tên NCC:");
        pnl_ThongTin.add(lb_TenNCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, -1, -1));

        btn_CapNhat.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_CapNhat.setText("Cập nhật");
        btn_CapNhat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_CapNhatMouseClicked(evt);
            }
        });
        pnl_ThongTin.add(btn_CapNhat, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 130, 130, -1));

        btn_ThemMoi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_ThemMoi.setText("Thêm mới");
        btn_ThemMoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ThemMoiMouseClicked(evt);
            }
        });
        pnl_ThongTin.add(btn_ThemMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, -1, -1));

        btn_XoaTrang.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_XoaTrang.setText("Xóa trắng");
        btn_XoaTrang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_XoaTrangMouseClicked(evt);
            }
        });
        pnl_ThongTin.add(btn_XoaTrang, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 130, 140, -1));

        txt_SDT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pnl_ThongTin.add(txt_SDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 10, 310, 40));

        txt_DiaChi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pnl_ThongTin.add(txt_DiaChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 60, 780, 40));

        txt_MaNCC.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_MaNCC.setEnabled(false);
        txt_MaNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_MaNCCActionPerformed(evt);
            }
        });
        pnl_ThongTin.add(txt_MaNCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 310, 40));

        txt_TenNCC.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pnl_ThongTin.add(txt_TenNCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, 330, 40));

        pnl_NCC_ThongTin.add(pnl_ThongTin, java.awt.BorderLayout.CENTER);

        pnl_TimKiem_NCC.setPreferredSize(new java.awt.Dimension(150, 70));
        pnl_TimKiem_NCC.setLayout(new java.awt.BorderLayout());

        txt_TimKiem_NCC.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        pnl_TimKiem_NCC.add(txt_TimKiem_NCC, java.awt.BorderLayout.CENTER);

        btn_TimKiem_NCC.setText("Tìm Kiếm");
        btn_TimKiem_NCC.setPreferredSize(new java.awt.Dimension(150, 150));
        btn_TimKiem_NCC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_TimKiem_NCCMouseClicked(evt);
            }
        });
        pnl_TimKiem_NCC.add(btn_TimKiem_NCC, java.awt.BorderLayout.EAST);

        pnl_NCC_ThongTin.add(pnl_TimKiem_NCC, java.awt.BorderLayout.SOUTH);

        pnl_DanhSachNCC.add(pnl_NCC_ThongTin, java.awt.BorderLayout.NORTH);

        pnl_NCC_Table.setLayout(new java.awt.BorderLayout());

        table_NCC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã NCC", "Tên NCC", "Địa chỉ", "Email", "SĐT"
            }
        ));
        table_NCC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_NCCMouseClicked(evt);
            }
        });
        scroll_NCC.setViewportView(table_NCC);

        pnl_NCC_Table.add(scroll_NCC, java.awt.BorderLayout.CENTER);

        pnl_DanhSachNCC.add(pnl_NCC_Table, java.awt.BorderLayout.CENTER);

        Tabbed_NhapHang.addTab("Danh sách NCC", pnl_DanhSachNCC);

        pnl_TaoPhieuNhap.setLayout(new java.awt.BorderLayout());

        pnl_DanhSachSP.setLayout(new java.awt.BorderLayout());

        table_DanhSachSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã SP", "Tên sản phẩm", "Số lượng nhập", "Đơn giá nhập", "Thành tiền"
            }
        ));
        scroll_DanhSachSP.setViewportView(table_DanhSachSP);

        pnl_DanhSachSP.add(scroll_DanhSachSP, java.awt.BorderLayout.CENTER);

        pnl_TaoPhieuNhap.add(pnl_DanhSachSP, java.awt.BorderLayout.CENTER);

        pnl_ThongTinNCC.setBorder(javax.swing.BorderFactory.createTitledBorder("Nhà cung cấp"));
        pnl_ThongTinNCC.setPreferredSize(new java.awt.Dimension(400, 10));
        pnl_ThongTinNCC.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Tổng tiền:");
        pnl_ThongTinNCC.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        cbo_DSNCC.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pnl_ThongTinNCC.add(cbo_DSNCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 260, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Nhà cung cấp:");
        pnl_ThongTinNCC.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        area_ghiChu.setColumns(20);
        area_ghiChu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        area_ghiChu.setRows(5);
        jScrollPane1.setViewportView(area_ghiChu);

        pnl_ThongTinNCC.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 260, 110));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Ghi chú:");
        pnl_ThongTinNCC.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        txt_TongTien.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_TongTien.setText("13.600.000");
        pnl_ThongTinNCC.add(txt_TongTien, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 260, 50));

        btn_TaoHoaDonNCC.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_TaoHoaDonNCC.setText("Tạo yêu cầu nhập hàng");
        btn_TaoHoaDonNCC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_TaoHoaDonNCCMouseClicked(evt);
            }
        });
        pnl_ThongTinNCC.add(btn_TaoHoaDonNCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 340, 70));

        jRadioButton1.setText("Đã nhận");
        pnl_ThongTinNCC.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, -1, -1));

        jRadioButton2.setText("Chưa nhận");
        pnl_ThongTinNCC.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        pnl_TaoPhieuNhap.add(pnl_ThongTinNCC, java.awt.BorderLayout.EAST);

        pnl_TimKiem.setPreferredSize(new java.awt.Dimension(200, 70));
        pnl_TimKiem.setLayout(new java.awt.BorderLayout());

        txt_TimKiem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_TimKiem.setText("Nhập mã SP...");
        pnl_TimKiem.add(txt_TimKiem, java.awt.BorderLayout.CENTER);

        btn_TimSP.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_TimSP.setText("Tìm kiếm");
        btn_TimSP.setPreferredSize(new java.awt.Dimension(150, 27));
        btn_TimSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_TimSPMouseClicked(evt);
            }
        });
        pnl_TimKiem.add(btn_TimSP, java.awt.BorderLayout.EAST);

        pnl_TaoPhieuNhap.add(pnl_TimKiem, java.awt.BorderLayout.NORTH);

        Tabbed_NhapHang.addTab("Tạo phiếu nhập hàng", pnl_TaoPhieuNhap);

        pnl_HoaDonNhapHang.setLayout(new java.awt.BorderLayout());

        pnl_Top.setPreferredSize(new java.awt.Dimension(0, 220));
        pnl_Top.setLayout(new java.awt.BorderLayout());

        pnl_HDNH_TimKiem.setPreferredSize(new java.awt.Dimension(10, 70));
        pnl_HDNH_TimKiem.setLayout(new java.awt.BorderLayout());

        jTextField2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextField2.setText("Nhập mã hóa đơn...");
        pnl_HDNH_TimKiem.add(jTextField2, java.awt.BorderLayout.CENTER);

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton3.setText("Tìm");
        jButton3.setPreferredSize(new java.awt.Dimension(150, 27));
        pnl_HDNH_TimKiem.add(jButton3, java.awt.BorderLayout.EAST);

        pnl_Top.add(pnl_HDNH_TimKiem, java.awt.BorderLayout.NORTH);

        pnl_BoLoc.setLayout(new java.awt.GridLayout(1, 3, 20, 0));

        pnl_LocNhanVien.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        pnl_LocNhanVien.setLayout(new javax.swing.BoxLayout(pnl_LocNhanVien, javax.swing.BoxLayout.Y_AXIS));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Lọc theo nhân viên");
        jPanel1.add(jLabel5);

        pnl_LocNhanVien.add(jPanel1);

        jTextField4.setText("Nhập số điện thoại NV...");
        jTextField4.setPreferredSize(new java.awt.Dimension(300, 50));
        jPanel2.add(jTextField4);

        pnl_LocNhanVien.add(jPanel2);

        pnl_BoLoc.add(pnl_LocNhanVien);

        pnl_LocNCC.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        pnl_LocNCC.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NCC 1", "NCC 2", "NCC 3", "NCC 4" }));
        pnl_LocNCC.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 330, 50));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Lọc theo NCC");
        pnl_LocNCC.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        pnl_BoLoc.add(pnl_LocNCC);

        pnl_LocTheoNgay.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        pnl_LocTheoNgay.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Lọc theo NCC");
        pnl_LocTheoNgay.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));
        pnl_LocTheoNgay.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 350, 50));

        pnl_BoLoc.add(pnl_LocTheoNgay);

        pnl_Top.add(pnl_BoLoc, java.awt.BorderLayout.CENTER);

        pnl_HoaDonNhapHang.add(pnl_Top, java.awt.BorderLayout.NORTH);

        pnl_Center.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Phiếu nhập", "Ngày nhập", "Người nhập", "Nhà cung cấp", "Trạng thái", "Tổng tiền", "In phiếu nhập"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        pnl_Center.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        pnl_HoaDonNhapHang.add(pnl_Center, java.awt.BorderLayout.CENTER);

        Tabbed_NhapHang.addTab("Hóa đơn nhập hàng", pnl_HoaDonNhapHang);

        add(Tabbed_NhapHang, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void table_NCCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_NCCMouseClicked
        // TODO add your handling code here:
        int r = table_NCC.getSelectedRow();
        
        if(r >= 0) {
            txt_MaNCC.setText(table_NCC.getValueAt(r, 0).toString());
            txt_TenNCC.setText(table_NCC.getValueAt(r, 1).toString());
            txt_SDT.setText(table_NCC.getValueAt(r, 4).toString());
            txt_Email.setText(table_NCC.getValueAt(r, 3).toString());
            txt_DiaChi.setText(table_NCC.getValueAt(r, 2).toString());
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn hàng muốn thao tác!!!");
        }
    }//GEN-LAST:event_table_NCCMouseClicked

    private void btn_ThemMoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ThemMoiMouseClicked
        // TODO add your handling code here:
        if(valiData_NCC()) {
            NhaCungCap ncc = createNCC();
            ArrayList<NhaCungCap> dsNCC = ncc_dao.getAllNCC();

            if(true) {
                if(ncc_dao.ThemNCC(ncc)) {
                    XoaDuLieuTableNCC();
                    DocDuLieuLenTableNCC();
                    JOptionPane.showMessageDialog(this, "Thêm thành công!!!");
                } else {
                    JOptionPane.showMessageDialog(this, "Thêm thất bai!!! Có lỗi xảy ra!!!");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Nhà cung cấp đã tồn tai!!!");
            }
        }
    }//GEN-LAST:event_btn_ThemMoiMouseClicked

    private void btn_TimKiem_NCCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_TimKiem_NCCMouseClicked
        // TODO add your handling code here:
        String maNCC_searched = txt_TimKiem_NCC.getText().toString();
        
        if(!maNCC_searched.trim().equals("")) {
            XoaDuLieuTableNCC();
            
            NhaCungCap ncc = ncc_dao.getNCC_TheoMa(maNCC_searched);
            
            DefaultTableModel temp = (DefaultTableModel) table_NCC.getModel();
            Object[] obj = {ncc.getMaNCC(), ncc.getTenNCC(), ncc.getDiaChi(), ncc.getEmail(), ncc.getSDT()};
            temp.addRow(obj);
        } else {
            XoaDuLieuTableNCC();
            DocDuLieuLenTableNCC();
        }
    }//GEN-LAST:event_btn_TimKiem_NCCMouseClicked

    private void btn_CapNhatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CapNhatMouseClicked
        // TODO add your handling code here:
        
        
        int r = table_NCC.getSelectedRow();
        if(r < 0) {
            JOptionPane.showMessageDialog(this, "Chọn NCC cần cập nhật!!!");
        } 
        
        if(valiData_NCC()) {
            String maNCC = txt_MaNCC.getText().toString();
            String tenNCC = txt_TenNCC.getText().toString();
            String email = txt_Email.getText().toString();
            String sDT = txt_SDT.getText().toString();
            String diaChi = txt_DiaChi.getText().toString();

            NhaCungCap ncc = new NhaCungCap(maNCC, tenNCC, diaChi, sDT, email);
            
            if(ncc_dao.CapNhatNCC(ncc)) {
                DefaultTableModel temp = (DefaultTableModel)table_NCC.getModel();
                temp.removeRow(r);
                Object[] obj = {ncc.getMaNCC(), ncc.getTenNCC(), ncc.getDiaChi(), ncc.getEmail(), ncc.getSDT()};
                temp.insertRow(r, obj);
                
                JOptionPane.showMessageDialog(this, "Cập nhật thành công NCC có mã = " + maNCC);
            } else {
                JOptionPane.showMessageDialog(this, "Cập nhật thất bai!!! Có lỗi xảy ra!!!");
            }
        }
        
    }//GEN-LAST:event_btn_CapNhatMouseClicked

    private void btn_XoaTrangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_XoaTrangMouseClicked
        // TODO add your handling code here:
        txt_MaNCC.setText("");
        txt_TenNCC.setText("");
        txt_DiaChi.setText("");
        txt_Email.setText("");
        txt_SDT.setText("");
        
        txt_MaNCC.setFocusable(true);
    }//GEN-LAST:event_btn_XoaTrangMouseClicked

    private void txt_MaNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_MaNCCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_MaNCCActionPerformed

    private void btn_TimSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_TimSPMouseClicked
        // TODO add your handling code here:
        String maSP = txt_TimKiem.getText();
        SanPham sp = sp_dao.getSP_TheoMa(maSP);
        
        
        if(maSP.compareTo("") != 0 && sp != null) {
//            tmp.add(sp);
//            tienVon += sp.getGiaNhapHang();
//            tongKM += sp.getkM().getLoaiKM().equals("LKM001") 
//                        ? sp.getGiaBan() * sp.getkM().getGiaTriKhuyenMai()
//                        : sp.getkM().getGiaTriKhuyenMai();
//            tongThue += sp.getThue();
            
            // Nhập số lượng sản phẩm
            int soLuong = Integer.parseInt(JOptionPane.showInputDialog(null, "Nhập số lượng", 0));
            
            // Tính tổng tiền thanh toán
            tongTien += sp.getGiaNhapHang()* soLuong;
            txt_TongTien.setText(tongTien + "");
            
            // Lấy số lượng hàng đang có
            int n = table_DanhSachSP.getModel().getRowCount();
            
            // Kiểm tra sản phẩm trùng lặp: cộng dồn số lượng và thành tiền
            for(int i = 0; i < n; ++i) {
                String maSP_Cheked = table_DanhSachSP.getModel().getValueAt(i, 0).toString();
                if(maSP_Cheked.compareTo(maSP) == 0) {
                    int soLuongHienTai = Integer.parseInt(table_DanhSachSP.getModel().getValueAt(i, 2).toString());
                    int soLuongMoi = soLuongHienTai + soLuong;
                    table_DanhSachSP.getModel().setValueAt(soLuongMoi, i, 2);
                    
                    
                    table_DanhSachSP.getModel().setValueAt(
                            Double.parseDouble(table_DanhSachSP.getValueAt(i, 3).toString()) * soLuongMoi, i, 4);
                    return;
                }
            }
            
            // Them sp vao giao hang
//            Object[] obj;
//                double donGia = sp.getGiaBan() * (1 - sp.getkM().getGiaTriKhuyenMai() + sp.getThue());
               Object[] obj = {sp.getMaSP(), sp.getTenSP(),  soLuong, 
                                        sp.getGiaNhapHang() ,sp.getGiaNhapHang() * soLuong};
               DefaultTableModel model_DSSP = (DefaultTableModel)table_DanhSachSP.getModel();
                model_DSSP.addRow(obj);
//            if(sp.getkM().getLoaiKM().equals("LKM001")) {
//            } else {
//                double donGia = sp.getGiaBan() * (1 - sp.getThue()) - sp.getkM().getGiaTriKhuyenMai();
//                Object[] obj = {sp.getMaSP(), sp.getTenSP(), sp.getLoaiSP(), soLuong, sp.getThue(), sp.getkM().getGiaTriKhuyenMai(), 
//                                        donGia ,donGia * soLuong};
//                model_DSSP = (DefaultTableModel)table_DanhSachSP.getModel();
//                model_DSSP.addRow(obj);
//            }
        } else {
            JOptionPane.showMessageDialog(null, "Không tìm thấy sản phẩm");
        }
    }//GEN-LAST:event_btn_TimSPMouseClicked

    public void XoaHetDuLieuSP_HDNH() {
        DefaultTableModel temp = (DefaultTableModel) table_DanhSachSP.getModel();
        temp.getDataVector().removeAllElements();
    }
    
    private void btn_TaoHoaDonNCCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_TaoHoaDonNCCMouseClicked
        // TODO add your handling code here:
        
        // Luu hoa don nhap hang
        String maHDNH = hdnh_dao.TuPhatSinhMa();
        int n = cbo_DSNCC.getSelectedIndex() + 1;
        String maNCC = n < 10 ? "NCC00" +  n
                : n < 100 ? "NCC0" + n
                : "NCC" + n;
        LocalDateTime ngayNhap = LocalDateTime.now();
        String ghiChu = area_ghiChu.getText();
        boolean isThanhToan = false;
        
        HoaDonNCC hdnh = new HoaDonNCC(maHDNH, new NhaCungCap(maNCC), ngayNhap, ghiChu, isThanhToan);
        if(hdnh_dao.ThemHDNCCVaoCSDL(hdnh)) {
            JOptionPane.showMessageDialog(this, "Lưu hóa đơn thành công!");
            
            // Luu chi tiet hoa don
            int soLuongSp = table_DanhSachSP.getRowCount();
            for(int i = 0; i < soLuongSp ; i++) {
                String maSP = table_DanhSachSP.getValueAt(i, 0).toString();
                String maHDNH_1 = maHDNH;
                int soLuong = Integer.parseInt(table_DanhSachSP.getValueAt(i, 2).toString());
                
                ChiTietHD_NCC temp = new ChiTietHD_NCC(new SanPham(maSP), new HoaDonNCC(maHDNH), soLuong);
                cthd_nh_dao.ThemVaoCSDL(temp);
            }
            
            area_ghiChu.setText("");
            cbo_DSNCC.setSelectedIndex(0);
            XoaHetDuLieuSP_HDNH();
        }
        
    }//GEN-LAST:event_btn_TaoHoaDonNCCMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Tabbed_NhapHang;
    private javax.swing.JTextArea area_ghiChu;
    private javax.swing.JButton btn_CapNhat;
    private javax.swing.JButton btn_TaoHoaDonNCC;
    private javax.swing.JButton btn_ThemMoi;
    private javax.swing.JButton btn_TimKiem_NCC;
    private javax.swing.JButton btn_TimSP;
    private javax.swing.JButton btn_XoaTrang;
    private javax.swing.JComboBox<NhaCungCap> cbo_DSNCC;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel lb_DiaChi;
    private javax.swing.JLabel lb_Email;
    private javax.swing.JLabel lb_MaNCC;
    private javax.swing.JLabel lb_SDT;
    private javax.swing.JLabel lb_TenNCC;
    private javax.swing.JPanel pnl_BoLoc;
    private javax.swing.JPanel pnl_Center;
    private javax.swing.JPanel pnl_DanhSachNCC;
    private javax.swing.JPanel pnl_DanhSachSP;
    private javax.swing.JPanel pnl_HDNH_TimKiem;
    private javax.swing.JPanel pnl_HoaDonNhapHang;
    private javax.swing.JPanel pnl_LocNCC;
    private javax.swing.JPanel pnl_LocNhanVien;
    private javax.swing.JPanel pnl_LocTheoNgay;
    private javax.swing.JPanel pnl_NCC_Table;
    private javax.swing.JPanel pnl_NCC_ThongTin;
    private javax.swing.JPanel pnl_TaoPhieuNhap;
    private javax.swing.JPanel pnl_ThongTin;
    private javax.swing.JPanel pnl_ThongTinNCC;
    private javax.swing.JPanel pnl_TimKiem;
    private javax.swing.JPanel pnl_TimKiem_NCC;
    private javax.swing.JPanel pnl_Top;
    private javax.swing.JScrollPane scroll_DanhSachSP;
    private javax.swing.JScrollPane scroll_NCC;
    private javax.swing.JTable table_DanhSachSP;
    private javax.swing.JTable table_NCC;
    private javax.swing.JTextField txt_DiaChi;
    private javax.swing.JTextField txt_Email;
    private javax.swing.JTextField txt_MaNCC;
    private javax.swing.JTextField txt_SDT;
    private javax.swing.JTextField txt_TenNCC;
    private javax.swing.JTextField txt_TimKiem;
    private javax.swing.JTextField txt_TimKiem_NCC;
    private javax.swing.JTextField txt_TongTien;
    // End of variables declaration//GEN-END:variables
}
