/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package quanlysach;

/**
 *
 * @author Asus
 */
public class Panel_staff extends javax.swing.JPanel {

    /**
     * Creates new form Panel_staff
     */
    public Panel_staff() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_ThongTinNhanVien = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pnl_BangThongTin = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        pnl_ThongTinNhanVien.setPreferredSize(new java.awt.Dimension(500, 200));
        pnl_ThongTinNhanVien.setRequestFocusEnabled(false);
        pnl_ThongTinNhanVien.setLayout(new javax.swing.BoxLayout(pnl_ThongTinNhanVien, javax.swing.BoxLayout.Y_AXIS));

        jLabel1.setText("jLabel1");
        pnl_ThongTinNhanVien.add(jLabel1);

        jLabel2.setText("jLabel2");
        pnl_ThongTinNhanVien.add(jLabel2);

        jLabel3.setText("jLabel3");
        pnl_ThongTinNhanVien.add(jLabel3);

        jLabel4.setText("jLabel4");
        pnl_ThongTinNhanVien.add(jLabel4);

        add(pnl_ThongTinNhanVien, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout pnl_BangThongTinLayout = new javax.swing.GroupLayout(pnl_BangThongTin);
        pnl_BangThongTin.setLayout(pnl_BangThongTinLayout);
        pnl_BangThongTinLayout.setHorizontalGroup(
            pnl_BangThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 805, Short.MAX_VALUE)
        );
        pnl_BangThongTinLayout.setVerticalGroup(
            pnl_BangThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 202, Short.MAX_VALUE)
        );

        add(pnl_BangThongTin, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel pnl_BangThongTin;
    private javax.swing.JPanel pnl_ThongTinNhanVien;
    // End of variables declaration//GEN-END:variables
}
